## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  #- nightly
# matrix:
#   allow_failures:
#     - julia: nightly
branches:
  only:
    - master
    #- /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email: false
git:
  depth: 99999999
jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate();
                                   Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs docs/make.jl
      after_success: skip
#after_success:
#  - julia -e 'import Pkg; cd(Pkg.dir("BitsFields")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
